lib/main.dart, lib/utilities/messageException.dart, lib/utilities/networkFunctions.dart
=> use subtype of exception in order to provide message

lib/screens/technicians/inventoryScreen.dart
=> Adapt filter buttons

lib/screens/technicians/organizationScreen.dart, lib/utilities/dataAction.dart, lib/utilities/networkFunctions.dart, lib/utilities/organizationalRelation.dart, lib/utilities/organizationalUnit.dart
=> Organizational units

lib/main.dart
closes #12 
honorable mention: @LuiseB31 
@nitelow did nothing. true.
=> revamp login screen

lib/screens/technicians/dashboardScreen.dart, lib/screens/technicians/inventoryScreen.dart
=> Refresh on resume

lib/screens/technicians/userManagementScreen.dart
=> sort user list

lib/screens/technicians/tabScreen.dart, lib/screens/technicians/technicianDeviceScreen.dart, lib/utilities/constants.dart, lib/utilities/networkFunctions.dart, lib/utilities/preferenceManager.dart
=> User selection

lib/screens/technicians/inventoryScreen.dart
=> revamp inventory filtering

lib/screens/technicians/userManagementScreen.dart
=> implement user creation as dialog

lib/screens/technicians/tabScreen.dart
=> fix user change

lib/main.dart, lib/screens/overviewScreen.dart, lib/screens/technicians/tabScreen.dart, lib/utilities/preferenceManager.dart
=> check for Hospital Preferences in Login

lib/screens/overviewScreen.dart
=> wrap layout in flexibles

lib/main.dart, lib/screens/overviewScreen.dart, lib/screens/technicians/tabScreen.dart, lib/screens/technicians/userManagementScreen.dart, lib/utilities/constants.dart, lib/utilities/preferenceManager.dart
=> Rearrange people screen

lib/main.dart, lib/screens/technicians/dashboardScreen.dart, lib/utilities/constants.dart, lib/utilities/dataAction.dart, lib/utilities/deviceStats.dart, lib/utilities/networkFunctions.dart
=> Show devices up for maintenance

lib/screens/deviceInfoScreen.dart
=> Report dialog

lib/screens/deviceInfoScreen.dart, lib/screens/overviewScreen.dart, lib/utilities/networkFunctions.dart
=> Organization filter dialog

lib/screens/technicians/organizationScreen.dart
=> Edit organisation units

lib/screens/overviewScreen.dart
=> Animate filtering

lib/screens/technicians/organizationScreen.dart, lib/utilities/hospitalDevice.dart, lib/utilities/networkFunctions.dart, lib/utilities/organizationalRelation.dart, lib/utilities/organizationalUnit.dart
=> Assign devices to departments

lib/screens/technicians/dashboardScreen.dart, lib/utilities/constants.dart
=> show days in state in todo list

lib/screens/technicians/maintenanceScreen.dart
=> implement list of devices

lib/main.dart, lib/screens/aboutScreen.dart, lib/screens/deviceInfoScreen.dart, lib/screens/organizationFilterView.dart, lib/screens/overviewScreen.dart, lib/screens/technicians/dashboardScreen.dart, lib/screens/technicians/inventoryScreen.dart, lib/screens/technicians/maintenanceScreen.dart, lib/screens/technicians/organizationScreen.dart, lib/screens/technicians/tabScreen.dart, lib/screens/technicians/technicianDeviceScreen.dart, lib/screens/technicians/userManagementScreen.dart, lib/utilities/country.dart, lib/utilities/detailedReport.dart, lib/utilities/deviceInfo.dart, lib/utilities/deviceStats.dart, lib/utilities/hospital.dart, lib/utilities/hospitalDevice.dart, lib/utilities/maintenanceEvent.dart, lib/utilities/networkFunctions.dart, lib/utilities/organizationalRelation.dart, lib/utilities/organizationalUnit.dart, lib/utilities/preferenceManager.dart, lib/utilities/previewDeviceInfo.dart, lib/utilities/report.dart, lib/utilities/shortDeviceInfo.dart, lib/utilities/swiftResponse.dart, lib/utilities/user.dart, pubspec.yaml
=> Null safety

lib/screens/technicians/organizationScreen.dart
=> always center buttons

lib/main.dart, lib/screens/deviceInfoScreen.dart, lib/screens/organizationFilterView.dart, lib/screens/technicians/dashboardScreen.dart, lib/screens/technicians/inventoryScreen.dart, lib/screens/technicians/maintenanceScreen.dart, lib/screens/technicians/organizationScreen.dart, lib/screens/technicians/tabScreen.dart, lib/screens/technicians/technicianDeviceScreen.dart, lib/screens/technicians/userManagementScreen.dart
=> replace deprecated attributes

lib/screens/technicians/inventoryScreen.dart, pubspec.lock, pubspec.yaml
=> Inventory list export

lib/screens/technicians/dashboardScreen.dart, lib/utilities/detailedReport.dart, lib/utilities/report.dart
=> localize time; add error handling

lib/screens/technicians/dashboardScreen.dart, lib/screens/technicians/inventoryScreen.dart
=> Increase device state contrast

lib/screens/technicians/organizationScreen.dart
=> make view scrollable in all directions

lib/screens/reportHistoryPlot.dart, lib/screens/technicians/dashboardScreen.dart, lib/screens/technicians/inventoryScreen.dart, lib/utilities/dataAction.dart, lib/utilities/networkFunctions.dart
=> Report history

lib/screens/technicians/dashboard_screen.dart
=> reverse todo list
